In [22]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt


df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [24]:


#Finding 0s and null
df[df['Glucose'] == 0]
df[df['BloodPressure'] == 0]
df[df['SkinThickness'] == 0]
df[df['Insulin'] == 0]
df[df['BMI'] == 0]
df[df['DiabetesPedigreeFunction'] == 0]
df[df['Age'] == 0]

df.isnull()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,False,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,False,False,False,False,False,False
767,False,False,False,False,False,False,False,False,False

In [65]:
from sklearn.model_selection import train_test_split

parameters = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
x = df[parameters].values
y = df['Outcome'].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 42)

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score, roc_auc_score

model = LogisticRegression(random_state= 42).fit(x_train, y_train)

y_predict = model.predict(x_test)

cm  = confusion_matrix(y_test, y_predict)

f1s = f1_score(y_test, y_predict)

prs = precision_score(y_test, y_predict)

res = recall_score(y_test, y_predict)

y_proba_std = model.predict_proba(x_test)[:, 1]
rcs = roc_auc_score(y_test, y_proba_std)

print("Confusion Matrix : \n", cm)
print("F1 Score :\t\t", f1s)
print("Precision Score :\t", prs)
print("Recall Score :\t\t", res)
print("ROC AUC Score :\t\t",rcs)

Confusion Matrix :
 [[84 15]
 [19 36]]
F1 Score :		 0.6792452830188679
Precision Score :	 0.7058823529411765
Recall Score :		 0.6545454545454545
ROC AUC Score :		 0.8442607897153351

/home/artifex/miniconda3/envs/ml_env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [54]:
#Data Scaling
max = df[parameters].max()
min = df[parameters].min()

for i in range(0, 8):
    print("Max: ", max[i])
    print("Min: ", min[i])
    print("")

Max:  17.0
Min:  0.0

Max:  199.0
Min:  44.0

Max:  122.0
Min:  24.0

Max:  99.0
Min:  7.0

Max:  846.0
Min:  14.0

Max:  67.1
Min:  18.2

Max:  2.42
Min:  0.078

Max:  81.0
Min:  21.0

/tmp/ipykernel_22266/2325562398.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Max: ", max[i])
/tmp/ipykernel_22266/2325562398.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Min: ", min[i])

In [68]:
#MIN MAX Scaling
df_minmax = pd.DataFrame()
parameters = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
               'DiabetesPedigreeFunction', 'Age']


df_minmax['Pregnancies']   = df['Pregnancies']/17
df_minmax['Glucose']       = df['Glucose']/199
df_minmax['BloodPressure'] = df['BloodPressure']/122
df_minmax['SkinThickness'] = df['SkinThickness']/99
df_minmax['Insulin']       = df['Insulin']/846
df_minmax['BMI']           = df['BMI']/67.1
df_minmax['DiabetesPedigreeFunction'] = df['DiabetesPedigreeFunction']/2.42
df_minmax['Age'] = df['Age']/81
df_minmax['Outcome'] = df['Outcome']

x_minmax = df_minmax[parameters].values
y_minmax = df_minmax['Outcome'].values

x_train_mm, x_test_mm, y_train_mm, y_test_mm = train_test_split(
                                               x_minmax, y_minmax, test_size=0.2, random_state=42)


model = LogisticRegression(random_state= 42).fit(x_train_mm, y_train_mm)

y_predict_mm = model.predict(x_test_mm)

cm  = confusion_matrix(y_test_mm, y_predict_mm)

f1s = f1_score(y_test_mm, y_predict_mm)

prs = precision_score(y_test_mm, y_predict_mm)

res = recall_score(y_test_mm, y_predict_mm)

y_proba_std = model.predict_proba(x_test_mm)[:, 1]
rcs = roc_auc_score(y_test, y_proba_std)


print("Confusion Matrix : \n", cm)
print("F1 Score :\t\t", f1s)
print("Precision Score :\t", prs)
print("Recall Score :\t\t", res)
print("ROC AUC Score :\t\t",rcs)

Confusion Matrix :
 [[88 11]
 [20 35]]
F1 Score :		 0.693069306930693
Precision Score :	 0.7608695652173914
Recall Score :		 0.6363636363636364
ROC AUC Score :		 0.846831955922865

In [64]:
#StandardScalar Scaling
from sklearn.preprocessing import StandardScaler

df_std = pd.DataFrame()

scaler = StandardScaler()


x_train, x_test, y_train, y_test = train_test_split(
                                               x, y, test_size=0.2, random_state=42)

x_train_std = scaler.fit_transform(x_train)
x_test_std  = scaler.transform(x_test)

model = LogisticRegression(random_state= 42, max_iter= 1000).fit(x_train_std, y_train)

y_predict_std = model.predict(x_test_std)

cm  = confusion_matrix(y_test, y_predict_std)

f1s = f1_score(y_test, y_predict_std)

prs = precision_score(y_test, y_predict_std)

res = recall_score(y_test, y_predict_std)

y_proba_std = model.predict_proba(x_test_std)[:, 1]
rcs = roc_auc_score(y_test, y_proba_std)

print("Confusion Matrix : \n", cm)
print("F1 Score :\t\t", f1s)
print("Precision Score :\t", prs)
print("Recall Score :\t\t", res)
print("ROC AUC Score :\t\t",rcs)

Confusion Matrix :
 [[83 16]
 [19 36]]
F1 Score :		 0.6728971962616822
Precision Score :	 0.6923076923076923
Recall Score :		 0.6545454545454545
ROC AUC Score :		 0.8440771349862258